spring:
  application:
    name: batch

  batch:
    job:
      enabled: false

  flyway:
    enabled: false  # (중요) 기본 Flyway Auto-run 끄고, 우리가 만든 authFlyway만 실행

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${BOARD_POSTGRESQL_URL}
    username: ${BOARD_POSTGRESQL_USERNAME}
    password: ${BOARD_POSTGRESQL_PASSWORD}

server:
  port: 8081
