spring:
  flyway:
    locations:
      - db/migration/dummy

logging:
  level:
    root: debug
    # JDK RMI transport, class-loader, and connector activities
    sun.rmi.transport.tcp: INFO
    sun.rmi.loader: INFO
    javax.management.remote.rmi: INFO